/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.yewton.testdiktat

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAgreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
